### ISSUE TITLE
支持通过偏移跳过脏数据

### ISSUE THREAD

**Issue by zema1** [zema1/suo5#11]
部分服务会在响应写入脏数据，需要跳过，可以尝试自己定位一下。

![image](https://user-images.githubusercontent.com/20637881/223613333-dd0547eb-3eb0-4532-a9e9-86f983d356c7.png)
![image](https://user-images.githubusercontent.com/20637881/223613396-68c0a2e0-8e2b-42f7-8d30-749edeb0995f.png)

**Comment by z0sen** [comment]
具体如何操作？今天碰到了这个情况

**Comment by zema1** [comment]
最新的 main 代码已经支持自动跳过脏数据了，还没发版，可以先自己编译一个试试。
不过我发现，使用 jsp 时，confluence 这种会在数据后面加脏数据的服务是没法用的，因为响应会被缓存住，没法变成一个流，suo5 就没法工作了。
我还发现，如果使用内存马，比如 filter/listener 形式的都可以绕过这个限制，也没有脏数据产生，如果遇到了这个问题可以用内存马来解决。
