### ISSUE TITLE
增加心跳包以避免 ReadTimeout 导致连接关闭

### ISSUE THREAD

**Issue by uknowsec** [zema1/suo5#12]
全双工模式下连接ssh，出现断线问题
测试半双工并未出现此问题

测试使用xshell和ssh连接都会出现掉线问题

日志信息：
```
运行日志
[INFO] 2023/03/10 16:11 header: 
User-Agent:  Mozilla/5.0 (Linux; Android 6.0; Nexus 5 Build/MRA58N) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/109.1.2.3
[INFO] 2023/03/10 16:11 method: POST
[INFO] 2023/03/10 16:11 testing connection with remote server
[INFO] 2023/03/10 16:11 connection to remote server successful
[INFO] 2023/03/10 16:11 checking the capability of FullDuplex..
[INFO] 2023/03/10 16:11 wow, you can run the proxy on FullDuplex mode
[INFO] 2023/03/10 16:11 tunnel created at mode full!
[INFO] 2023/03/10 16:11 new connection from 127.0.0.1:51770
[INFO] 2023/03/10 16:11 handshake success 127.0.0.1:51770
[DBUG] 2023/03/10 16:11 recv dial response from server: length: 7
[INFO] 2023/03/10 16:11 conn successfully connected to 192.168.247.206:22
[DBUG] 2023/03/10 16:11 write data, length: 50
[DBUG] 2023/03/10 16:11 write data, length: 2072
[DBUG] 2023/03/10 16:11 write data, length: 48
[DBUG] 2023/03/10 16:11 write data, length: 16
[DBUG] 2023/03/10 16:11 write data, length: 44
[DBUG] 2023/03/10 16:11 write data, length: 60
[DBUG] 2023/03/10 16:11 write data, length: 76
[DBUG] 2023/03/10 16:11 write data, length: 52
[DBUG] 2023/03/10 16:11 write data, length: 108
[DBUG] 2023/03/10 16:11 write data, length: 128
[DBUG] 2023/03/10 16:11 remote readwriter closed
[DBUG] 2023/03/10 16:11 local conn closed
[INFO] 2023/03/10 16:11 connection from 127.0.0.1:51770 closed

```

**Comment by uknowsec** [comment]
同样测试mstsc链接rdp也出现掉线问题
`[INFO] 2023/03/10 16:28 conn successfully connected to 192.168.247.202:3389
[DBUG] 2023/03/10 16:28 write data, length: 47
[DBUG] 2023/03/10 16:28 write data, length: 186
[DBUG] 2023/03/10 16:28 write data, length: 93
[DBUG] 2023/03/10 16:28 write data, length: 86
[DBUG] 2023/03/10 16:28 write data, length: 644
[DBUG] 2023/03/10 16:28 write data, length: 105
[DBUG] 2023/03/10 16:28 write data, length: 491
[DBUG] 2023/03/10 16:28 write data, length: 78
[DBUG] 2023/03/10 16:28 write data, length: 41
[DBUG] 2023/03/10 16:28 write data, length: 41
[DBUG] 2023/03/10 16:28 write data, length: 41
[DBUG] 2023/03/10 16:28 write data, length: 41
[DBUG] 2023/03/10 16:28 write data, length: 41
[DBUG] 2023/03/10 16:28 write data, length: 41
[DBUG] 2023/03/10 16:28 write data, length: 41
[DBUG] 2023/03/10 16:28 write data, length: 694
[DBUG] 2023/03/10 16:28 write data, length: 55
[DBUG] 2023/03/10 16:28 write data, length: 708
[DBUG] 2023/03/10 16:28 write data, length: 203
[DBUG] 2023/03/10 16:28 write data, length: 85
[DBUG] 2023/03/10 16:28 write data, length: 69
[DBUG] 2023/03/10 16:28 write data, length: 55
[DBUG] 2023/03/10 16:28 write data, length: 57
[DBUG] 2023/03/10 16:28 write data, length: 57
[DBUG] 2023/03/10 16:28 write data, length: 105
[DBUG] 2023/03/10 16:28 write data, length: 57
[DBUG] 2023/03/10 16:28 write data, length: 114
[DBUG] 2023/03/10 16:28 write data, length: 61
[DBUG] 2023/03/10 16:28 write data, length: 64
[DBUG] 2023/03/10 16:28 write data, length: 64
[DBUG] 2023/03/10 16:28 write data, length: 61
[DBUG] 2023/03/10 16:28 write data, length: 57
[DBUG] 2023/03/10 16:28 write data, length: 57
[DBUG] 2023/03/10 16:28 remote readwriter closed
[DBUG] 2023/03/10 16:28 local conn closed
[INFO] 2023/03/10 16:28 connection from 127.0.0.1:52569 closed`

**Comment by zema1** [comment]
看了一下这个问，是因为没有数据传输，被 Server 主动关闭了连接。打算在 suo5 中加一个心跳包，这样服务端就不会 readtimeout。在 suo5 实现这个功能之前，可以先改一下本地的 ssh 文件，让 ssh 自己发送心跳：

编辑一下 `~/.ssh/config` 文件，加入一行
```
ServerAliveInterval 5
```
就可以让 ssh 每 5s 发送一个心跳包，实测可用
