### ISSUE TITLE
负载均衡模式下流量无法集中

### ISSUE THREAD

**Issue by quithake** [zema1/suo5#15]
一直报错 error read response frame, frame is too big, 1013478509, connection goes to shutdown

**Comment by zema1** [comment]
1. 用的是最新版吗，目标是什么环境，这个问题可否本地复现
3. `-r` 参数填写的是什么参数，这个需要写一个 url，填写实际的没有反代的 suo5 的地址，比如 `http://10.3.0.2:8080/code/suo5.jsp`，这个填错了是不行的
4. 是否已经尽可能的把所有后端服务上传了 suo5 的服务端

**Comment by zema1** [comment]
我本地测试用的是这个环境，至少这里是没问题的 `https://github.com/zema1/suo5/tree/main/tests/nginx-tomcat-load-balance`，你可以测试一下试试

**Comment by quithake** [comment]
1.是最新版，目标weblogic环境
2.-r 填的就是内网地址
3.已经尽可能全部上传了
4.同样情况下reg可以代理成功

**Comment by zema1** [comment]
感谢师傅反馈，我测一下 weblogic 试试

**Comment by zema1** [comment]
师傅可以测试一下这个 PR 里面的 suo5.jsp  https://github.com/zema1/suo5/pull/18

**Comment by zema1** [comment]
Fixed in https://github.com/zema1/suo5/releases/tag/v0.6.0
