### ISSUE TITLE
got unexpected body, remote server test failed

### ISSUE THREAD

**Issue by P1a0z1** [zema1/suo5#16]
got unexpected body, remote server test failed  这是什么错误呢

![image](https://user-images.githubusercontent.com/40374872/226554592-a3c39bea-1888-44ce-9fbc-773b0655a2a4.png)

**Comment by zema1** [comment]
看起来好像是 suo5 没执行成功，如果能本地复现可以在这里贴一下复现方法，我会尽快看下。

如果是授权测试，方便的话可以私信我微信看下 b64: `emVtYWw2NjY=`

**Comment by zema1** [comment]
没有继续提供其他信息了，先关闭了，如果有后续可以新开 issue
