### ISSUE TITLE
一个让性能飞起来的建议

### ISSUE THREAD

**Issue by hktalent** [zema1/suo5#17]
使用github.com/lucas-clemente/quic-go/http3
也就是quic协议，性能飞更快

非常好的开源,加油

**Comment by zema1** [comment]
http3 国内生产环境基本都没使用，甚至 http2 都没普及，为了兼容性考虑，这个短时间内不会做。

不过倒是提醒了我，在半双工模式，可以看看能否 upgrade 到 http2，如果远端支持，性能会接近全双工

**Comment by hktalent** [comment]
可以再提供一个client啊，不需要走浏览器
