### ISSUE TITLE
HTTP/S Proxy upstream support

### ISSUE THREAD

**Issue by alexgabbard01** [zema1/suo5#23]
According to manual:

--proxy value  use upstream socks5 proxy

Does suo5 support Socks5 proxy only as upstream? Is HTTP/S or Squid Proxy supported?

**Comment by zema1** [comment]
Right now, the code only allows for SOCKS5 proxies, but I'm thinking that HTTP(S) proxies can also be supported. I'll double-check and if everything looks good, I'll lift the restriction.

**Comment by alexgabbard01** [comment]
Okay cool. I will also test if HTTP(S) proxies can be used

**Comment by alexgabbard01** [comment]
Only socks5 is supported, i did test it and verified it.
![suo5 error](https://user-images.githubusercontent.com/118827010/236941060-809f9d23-7dab-4f2e-a8e0-683c403494ec.png)

**Comment by alexgabbard01** [comment]
Only socks5 is supported, i did test it and verified it.

![suo5 error](https://user-images.githubusercontent.com/118827010/236941662-62366f12-3966-4d82-bc16-41bc2412241e.png)

**Comment by zema1** [comment]
I removed this restriction  from the code https://github.com/zema1/suo5/commit/e941463383c72878b99419034672ddcf9f4e4571, so now you can use socks5 and http(s) as upstream proxies. Before the official release, you can test the binary compiled by the Github Action, or compile the code from the main branch manually. If you encounter any issues, feel free to comment here.

Use `target-release` in github action: [https://github.com/zema1/suo5/actions/runs/4924332131](https://github.com/zema1/suo5/actions/runs/4924332131)

![image](https://user-images.githubusercontent.com/20637881/237050794-904511be-c6ce-41a6-8e83-0778e67c9062.png)

**Comment by zema1** [comment]
related to https://github.com/zema1/suo5/issues/25
Add in https://github.com/zema1/suo5/releases/tag/v0.7.0
