### ISSUE TITLE
兼容性问题

### ISSUE THREAD

**Issue by veo** [zema1/suo5#24]
1.兼容性比较差，尝试改各种类型的内存马都无法使用，只有jsp能正常使用
2.改内存马很麻烦，有很多request或response，容易找不到方法不方便使用，需要都再改成反射

neo我改了几个内存马都一步到位
https://github.com/L-codes/Neo-reGeorg/blob/master/templates/NeoreGeorg.java

但是suo一直没成功，改完如图，所有包都是一个s的响应包，而且很慢才回一个包

![image](https://github.com/zema1/suo5/assets/38176360/97e115a9-55d8-423d-9d8e-1a9ae1b59123)

**Comment by zema1** [comment]
师傅加一下我微信，在项目readme有，我们微信聊下看看什么问题
