### ISSUE TITLE
Basic Authentication support

### ISSUE THREAD

**Issue by alexgabbard01** [zema1/suo5#25]
I love the new implementation of upstream HTTP{s) proxy support as an addition to the previous only-Socks5 upstream. However this HTTPS(s) implementation is not fine-tuned, because it does not support an authenticated Squid proxy.

I did try to insert proxy authentication credentials via Proxy-Authorization header, but suo5 doesn't parse these credentials to the proxy that I'm using.

I mean in this time and age no one uses an unauthenticated proxy, that may end up being abused by bots or evil users who would buy drugs on Silk Road or watch child porn or perform other illegal activities using the proxy.

For that matter I feel compelled to raise this issue so you can implement Basic Authentication mechanism on suo5.

The only Proxy auth support that this tool support as stated:  "--auth value  --->>> socks5 creds, username:password, leave empty to auto generate", which is insufficient for my use case, I also need the upstream proxy to be supported if it has username and password, as public Squid proxies are not authenticated.

![suo1](https://github.com/zema1/suo5/assets/118827010/21bc658b-9271-4e0d-85ff-f515db2bd062)

At first, when using an authenticated Squid proxy, suo5 looks like it will respect the Proxy-Authorization header to which i sent proxy authentication credentials, as it does not throw an error.

But when when I configure Firefox to use a Socks5 proxy created by suo5 (127.0.0.1:1111), it becomes evident that suo5 doees not support authenticated proxies as it throws 407 error instead of 200 ok.

![suo2](https://github.com/zema1/suo5/assets/118827010/19052c70-284e-4043-9c2f-d1ed551a6afa)

Please consider supporting user:pass for upstream proxies, be it Socks5 or Squid proxy

**Comment by zema1** [comment]
I get it. Have you ever tried this format: `--proxy socks5://user:pass@host:port` or `--proxy http://user:pass@host:port` ? The proxy supports configuring authentication methods. I tested the authentication for socks5 locally and it worked fine, and I think http proxy should also work.

![image](https://github.com/zema1/suo5/assets/20637881/6591762a-ddbd-46af-9aa7-6404ba25b8c4)

I created a socks5 proxy with authentication using suo5. Then, I opened a new pane and connected again using the socks5 proxy created earlier, and everything worked fine.

**Comment by zema1** [comment]
The `--header` flag does not work with `--proxy`. This option is used for sending headers to the remote target.

**Comment by alexgabbard01** [comment]
> The `--header` flag does not work with `--proxy`. This option is used for sending headers to the remote target.

Why would not a custom header work with an upstream Squid proxy? It does work, but you never implemented it on suo. Take a look at https://github.com/L-codes/Neo-reGeorg/blob/master/README-en.md

You can learn one or two things from there

**Comment by zema1** [comment]
I believe `--proxy http://user:pass@host:port` is what you want.  Credentials will be auto parsed to a valid `Proxy-Authorization` header. If this can't meet your needs. Let me know and I will try to make --header works on --proxy.  Thanks for your advice.
