### ISSUE TITLE
更新到0.7.0后，连接失败 read tcp xxxx  i/o timeout

### ISSUE THREAD

**Issue by saobee** [zema1/suo5#29]
[FTAL] 05-19 17:06 ReadStatusLine: read tcp 192.168.3.35:33886->xxx.xxx.xxx.xxx:80: i/o timeout

可以确定和https没有关系，我这就是80端口的。

换为使用0.6.0的客户端连接 0.7.0的suo5.jsp没问题。

补充一下，服务端是用宝塔搭建，windows 2008 server，当然，之前肯定是正常使用的

**Comment by zema1** [comment]
fixed in: https://github.com/zema1/suo5/releases/tag/v0.8.0

Thanks
