### ISSUE TITLE
Resin环境下适配有问题

### ISSUE THREAD

**Issue by HHa1ey** [zema1/suo5#30]
测试在Resin4的环境下代理不会生效

**Comment by zema1** [comment]
测试里有 resin4 的环境，用的 https://hub.docker.com/r/expertsystems/resin 是正常工作的。能提供一个可以复现的环境吗

**Comment by HHa1ey** [comment]
> 测试里有 resin4 的环境，用的 https://hub.docker.com/r/expertsystems/resin 是正常工作的。能提供一个可以复现的环境吗

环境是泛微OA自带的Resin4，不知道是不是泛微环境影响的。

**Comment by zema1** [comment]
这个试了下，用内存马可以，jsp 无法使用不是 bug，可以看看这里的说明 https://github.com/zema1/suo5/tree/main/assets
