### ISSUE TITLE
支持 Spring Webflux 

### ISSUE THREAD

**Issue by zema1** [zema1/suo5#33]

**Comment by 1n7erface** [comment]
<img width="1118" alt="image" src="https://github.com/zema1/suo5/assets/52184829/22129c31-fdd4-46eb-833d-f1cf5cb8d73e">
请问在webflux环境下这里的request参数如何处理

**Comment by zema1** [comment]
webflux这个写起来有点麻烦，我尝试写了一版，但全双工的支持还有点小问题，如果有人对响应式编程比较熟悉，可以找我讨论下

**Comment by 1n7erface** [comment]
目前遇到问题?我想着是把用到request和response的Api做转换，这种不行吗？

**Comment by zema1** [comment]
应该不太行，我试过直接转换似乎会卡住。我目前只用响应式写法实现了半双工的逻辑，全双工流量传输会一卡一卡的，还没找到原因

**Comment by yuweibo** [comment]
jdk21出来了，用虚拟线程就行；我测试了下，可以大约减少一百个线程，是因为new Socket目前有问题，改善这块儿就没问题了

**Comment by zema1** [comment]
没法用高版本的 jdk，为了能兼容目标环境，需要尽可能降低 jdk。我最近空了会把之前写的发上来，有兴趣的师傅可以继续研究

**Comment by zema1** [comment]
> 没法用高版本的 jdk，为了能兼容目标环境，需要尽可能降低 jdk。我最近空了会把之前写的发上来，有兴趣的师傅可以继续研究

解决了，写了一堆响应式逻辑，完美运行了

**Comment by 1n7erface** [comment]
大佬牛逼的～
