### ISSUE TITLE
加密是安全的吗？

### ISSUE THREAD

**Issue by aquamise** [zema1/suo5#34]
在其他网站上看到的描述说是密钥会在数据中传输？对于中间人是安全的吗？

**Comment by zema1** [comment]
suo5用的只是一个简单的私有协议，没有密钥的概念，其本身是可以被中间人的。如果原站点是 https，那么基本没有中间人问题。。不过为什么会有问到这个问题呢，中间人似乎不是这个工具该考虑的事
