### ISSUE TITLE
是不是其他人只要知道jsp文件的地址，就能进内网

### ISSUE THREAD

**Issue by lovelyjuice** [zema1/suo5#38]
Neo-reGeorg 是需要密码才能连接的

**Comment by hi-unc1e** [comment]
是的， 如果你使用的是默认JSP的话。

不过，鉴于你问的其实是这个jsp的鉴权机制， 作者倒是提供一种办法，自定义UserAgent
- 修改JSP中的User-Agent参数：https://github.com/zema1/suo5/blob/main/assets/suo5.jsp#L24
- 客户端连接的时候指定`--ua value`

**Comment by zema1** [comment]
assets 中写了一下目前的认证机制
