### ISSUE TITLE
got unexpected body, remote server test failed

### ISSUE THREAD

**Issue by cuiyimeng** [zema1/suo5#50]
got unexpected body, remote server test failed，我看issus里面出现过同样的问题但是都被关闭了，请问是如何解决的

**Comment by cuiyimeng** [comment]
<img width="520" alt="image" src="https://github.com/zema1/suo5/assets/25096779/0d4cf258-303c-413d-bf52-2312bcb36dbd">

**Comment by zema1** [comment]
脚本/内存马 没生效吧
