### ISSUE TITLE
如果是HTTPS的网站这种数据传输会被G/F/W识别吗？

### ISSUE THREAD

**Issue by opser-gavin** [zema1/suo5#51]
如题，如果我是在一个国外的HTTPS网站上做这个，那么可以用这个做为翻墙工具吗？ 会被GFW识别吗？
稳定性杂样，或者除了HTTPS本身加密外这软件有没可能再做一层加密呢？

**Comment by zema1** [comment]
这个项目并未做这个方向的考虑，也没有做很多流量层的对抗，不太合适作为此类工具。

不过稳定性应该还好
