### ISSUE TITLE
error read response frame, frame is too big, 2065852012, connection goes to shutdown

### ISSUE THREAD

**Issue by bcdlbgm** [zema1/suo5#54]
error read response frame, frame is too big, 2065852012, connection goes to shutdown
脚本解析了在server，suo5gui显示连接成功了，但使用时suo5日志会出现上面那种error。

**Comment by zema1** [comment]
这种一般来说就是用不了，不过现在这个打印的数据让人比较费解，需要优化下输出

**Comment by zema1** [comment]
细看了一下，这个如果确认正常解析了，但是用的时候出这个问题，大概率是因为有负载均衡，某些包发到错误的节点上去了。需要尽量把每个节点都上一下 suo5，然后开启 suo5 的流量转发功能
