### ISSUE TITLE
The type java.util.Map$Entry cannot be resolved. It is indirectly referenced from required .class files

### ISSUE THREAD

**Issue by SAMOxtan** [zema1/suo5#57]
环境：weblogic10 + jdk1.8.0_181
错误：The type java.util.Map$Entry cannot be resolved. It is indirectly referenced from required .class files
![image](https://github.com/zema1/suo5/assets/35799367/265b1678-d089-489a-865a-a233d999b3fa)

**Comment by zema1** [comment]
大概看了一下，猜测是 JDK 和 weblogic 之间某些奇怪的版本不兼容导致的，由于 CI 里又 10.3.6 的 weblogic 测试是正常工作的，我也不知如何解决这个好。

但可以确定的是，不用 jsp，而是使用内存马的方式是没问题，建议使用内存马的形式打入 suo5
