### ISSUE TITLE
1.3版本aspx问题

### ISSUE THREAD

**Issue by Unveiling9** [zema1/suo5#72]
1.3版本aspx代理提示连接成功，但随后就提示context deadline exceeded (Client.Timeout exceeded while awaiting headers)，无法正常访问内网资源
![1 3](https://github.com/user-attachments/assets/abe0cb93-9538-430b-93e5-45990cb886fe)

1.2版本 aspx代理正常使用

![1 2](https://github.com/user-attachments/assets/6542d51d-f389-44fa-b0a3-defeca25def0)

**Comment by zema1** [comment]
这个大概率是默认启用 cookiejar 导致的，可以先暂时禁用掉 cookiejar 来解决

- 命令行 `--no-jar`
- GUI 版在高级设置里有

更进一步的，感觉是某些版本的 iis 和 PHP 一样有 session 锁，最近想办法解决一下
