### ISSUE TITLE
大佬帮忙看下符合我这个需求吗？

### ISSUE THREAD

**Issue by checkToke** [zema1/suo5#74]
代理服务商提供获取代理信息的api接口，这个接口每次提供一个30秒有效期的代理信息
我想自己搭建一个隧道代理，每一个到达隧道代理的请求都会自动请求代理服务商的代理
不胜感激！！！

**Comment by ycrao** [comment]
并不符合，你可以认为它是菜刀 webshell 之类工具（但你自己知晓且主动部署的），不具有自动切换代理的功能，可以自行编码实现。

**Comment by zema1** [comment]
上面的师傅帮忙回答了，能实现你需求的工具有很多，但这个项目并不适合作为常规意义上的代理工具来使用，
