### ISSUE TITLE
auth没生效 Mac os

### ISSUE THREAD

**Issue by K1p2y3** [zema1/suo5#8]
<img width="704" alt="图片" src="https://user-images.githubusercontent.com/40665473/222348181-0efa7e66-69d2-41e6-b4ba-30341560a517.png">

**Comment by zzgxpyy** [comment]
加一条Question:./suo5-linux-amd64 -t http://10.37.200.6:8099/s.jsp  --timeout 600 --auth abc:abc123
Linux也同样没生效，同时--timeout参数也没有生效。还是default的10s就断了。

**Comment by zema1** [comment]
> 加一条Question:./suo5-linux-amd64 -t http://10.37.200.6:8099/s.jsp --timeout 600 --auth abc:abc123 Linux也同样没生效，同时--timeout参数也没有生效。还是default的10s就断了，另外问一嘴，代码本身页面可以加一个key认证吗？防止扫地僧。

auth 和 timeout 参数的问题明天看下。

认证这个暂时不打算加，实际上可以通过改一下 UA 来防止别人上车，UA 不对是连不上的，注意：改 UA 需要 `suo5.jsp` 和客户端同步修改。

另外 suo5 在实战中更建议通过内存马的方式来使用。

**Comment by zema1** [comment]
认证参数不生效的问题会在 0.4.0 中修复。

timeout 的我看了一遍，应该是生效的。timeout 这个实际上也受远端的配置控制，如果目标服务器设置了最大超时时间，连接也会被关闭，感觉你说的可能是这种情况，如果确认不是这个原因，可以新开 issue 讨论。 @zzgxpyy
